[[headers]]
for = "*.js"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "*.jsx"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "*.json"
[headers.values]
Content-Type = "application/json"

[[headers]]
for = "*.json"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/*" # Apply to all paths
  [headers.values]
    Access-Control-Allow-Origin = "*" # Allow all origins
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
    Access-Control-Allow-Headers = "Authorization, Content-Type, X-Requested-With"
    Access-Control-Allow-Credentials = "true"

[[headers]]
  for = "/*" # Specific CORS headers for https://asioso.coyocloud.com
  [headers.values]
    Access-Control-Allow-Origin = "https://asioso.coyocloud.com"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  force = true
  from = "/api/*"
  to = "https://asioso.coyocloud.com/api/:splat"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
