[[headers]]
for = "/pluginAdapter.js"
[headers.values]
  Content-Type = "application/javascript"

[[headers]]
for = "/*.js"
[headers.values]
  Content-Type = "application/javascript"

[[headers]]
for = "/*.mjs"
[headers.values]
  Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
