[[headers]]
for = "*.js"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "*.jsx"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "*.json"
[headers.values]
Content-Type = "application/json"
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
    Access-Control-Allow-Headers = "Authorization, Content-Type, X-Requested-With"
    Access-Control-Allow-Credentials = "true"

[[headers]]
for = "/api/*"
[headers.values]
Content-Type = "application/json" # Ensure correct MIME type
Access-Control-Allow-Origin = "*" # Allow all origins
Access-Control-Allow-Methods = "GET, OPTIONS, POST, PUT, DELETE"
Access-Control-Allow-Headers = "Authorization, Content-Type, X-Requested-With"

[[headers]]
for = "/*"
[headers.values]
  Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval'; object-src 'none';"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
  Access-Control-Allow-Headers = "Authorization, Content-Type, X-Requested-With"

[[redirects]]
  from = "/users"
  to = "https://asioso.coyocloud.com/api/user" # Directly proxy to Haiilo API
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://asioso.coyocloud.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/lifecycle/*"
  to = "/.netlify/functions/lifecycle" # Route lifecycle events to a Netlify function
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { request.path != "/users" } # Exclude /users from being redirected to index.html

[functions]
  directory = "netlify/functions"