[[headers]]
for = "*.json"
[headers.values]
Content-Type = "application/json"
Access-Control-Allow-Origin = "*" # Allow all origins
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"

